//Get carousel content config
export const GET_CAROUSEL_CONFIG_INIT = "GET_CAROUSEL_CONFIG_INIT";
export const GET_CAROUSEL_CONFIG_SUCCESS = "GET_CAROUSEL_CONFIG_SUCCESS";
export const GET_CAROUSEL_CONFIG_FAIL = "GET_CAROUSEL_CONFIG_FAIL";
